### ISSUE TITLE
Redirect ladybug.dev/rss.xml

### ISSUE THREAD

**Issue by aspittel** [ladybug-podcast/ladybugpodcast#34]
This should probably redirect to the pinecast RSS so people don't accidentally subscribe to this feed that we haven't fully implemented

**Comment by nikoheikkila** [comment]
Are you deploying to Netlify? In that case, a relevant rule could be placed to the `netlify.toml` file. I could work on it.

Something like below could work.

```toml
[[redirects]]
  from = "/rss.xml"
  to = "https://pinecast.com/feed/ladybug-podcast"
  status = 301
```
